/*
 * CAEP SSF API
 * CAEP.dev Receiver SSF API
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: hello@caep.dev
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.AddSubjectRequest;
import io.swagger.client.model.CreateStreamRequest;
import io.swagger.client.model.CreateStreamResponse;
import io.swagger.client.model.PollEventsRequest;
import io.swagger.client.model.PollEventsResponse;
import io.swagger.client.model.RemoveSubjectRequest;
import io.swagger.client.model.StatusResponse;
import io.swagger.client.model.UpdateStatusRequest;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for DefaultApi
 */
@Ignore
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    /**
     * 
     *
     * Get the status of the stream with CAEP transmitter.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void statusGetTest() throws Exception {
        String streamId = null;
        StatusResponse response = api.statusGet(streamId);

        // TODO: test validations
    }
    /**
     * 
     *
     * Update the stream status to the CAEP transmitter.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void statusPostTest() throws Exception {
        UpdateStatusRequest body = null;
        StatusResponse response = api.statusPost(body);

        // TODO: test validations
    }
    /**
     * 
     *
     * Poll and/or acknowledge events from the stream.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void streamsPollPostTest() throws Exception {
        PollEventsRequest body = null;
        PollEventsResponse response = api.streamsPollPost(body);

        // TODO: test validations
    }
    /**
     * 
     *
     * create a stream with CAEP transmitter.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void streamsPostTest() throws Exception {
        CreateStreamRequest body = null;
        CreateStreamResponse response = api.streamsPost(body);

        // TODO: test validations
    }
    /**
     * 
     *
     * Add a subject to be listened by the stream.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void subjectsaddPostTest() throws Exception {
        AddSubjectRequest body = null;
        api.subjectsaddPost(body);

        // TODO: test validations
    }
    /**
     * 
     *
     * Remove a listened subject from the stream.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void subjectsremovePostTest() throws Exception {
        RemoveSubjectRequest body = null;
        api.subjectsremovePost(body);

        // TODO: test validations
    }
}
