/*
 * CAEP SSF API
 * CAEP.dev Receiver SSF API
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: hello@caep.dev
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.Delivery;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * CreateStreamRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-12-07T14:46:31.358537509Z[GMT]")

public class CreateStreamRequest {
  @SerializedName("delivery")
  private Delivery delivery = null;

  @SerializedName("event_requested")
  private List<String> eventRequested = new ArrayList<String>();

  @SerializedName("description")
  private String description = null;

  public CreateStreamRequest delivery(Delivery delivery) {
    this.delivery = delivery;
    return this;
  }

   /**
   * Get delivery
   * @return delivery
  **/
  @Schema(required = true, description = "")
  public Delivery getDelivery() {
    return delivery;
  }

  public void setDelivery(Delivery delivery) {
    this.delivery = delivery;
  }

  public CreateStreamRequest eventRequested(List<String> eventRequested) {
    this.eventRequested = eventRequested;
    return this;
  }

  public CreateStreamRequest addEventRequestedItem(String eventRequestedItem) {
    this.eventRequested.add(eventRequestedItem);
    return this;
  }

   /**
   * Get eventRequested
   * @return eventRequested
  **/
  @Schema(required = true, description = "")
  public List<String> getEventRequested() {
    return eventRequested;
  }

  public void setEventRequested(List<String> eventRequested) {
    this.eventRequested = eventRequested;
  }

  public CreateStreamRequest description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateStreamRequest createStreamRequest = (CreateStreamRequest) o;
    return Objects.equals(this.delivery, createStreamRequest.delivery) &&
        Objects.equals(this.eventRequested, createStreamRequest.eventRequested) &&
        Objects.equals(this.description, createStreamRequest.description);
  }

  @Override
  public int hashCode() {
    return Objects.hash(delivery, eventRequested, description);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateStreamRequest {\n");
    
    sb.append("    delivery: ").append(toIndentedString(delivery)).append("\n");
    sb.append("    eventRequested: ").append(toIndentedString(eventRequested)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
