/*
 * CAEP SSF API
 * CAEP.dev Receiver SSF API
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: hello@caep.dev
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
/**
 * PollEventsResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-12-07T14:46:31.358537509Z[GMT]")

public class PollEventsResponse {
  @SerializedName("sets")
  private Map<String, Object> sets = null;

  public PollEventsResponse sets(Map<String, Object> sets) {
    this.sets = sets;
    return this;
  }

  public PollEventsResponse putSetsItem(String key, Object setsItem) {
    if (this.sets == null) {
      this.sets = new HashMap<String, Object>();
    }
    this.sets.put(key, setsItem);
    return this;
  }

   /**
   * Get sets
   * @return sets
  **/
  @Schema(description = "")
  public Map<String, Object> getSets() {
    return sets;
  }

  public void setSets(Map<String, Object> sets) {
    this.sets = sets;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PollEventsResponse pollEventsResponse = (PollEventsResponse) o;
    return Objects.equals(this.sets, pollEventsResponse.sets);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sets);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PollEventsResponse {\n");
    
    sb.append("    sets: ").append(toIndentedString(sets)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
