/*
 * CAEP SSF API
 * CAEP.dev Receiver SSF API
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: hello@caep.dev
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * PollEventsRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-12-07T14:46:31.358537509Z[GMT]")

public class PollEventsRequest {
  @SerializedName("maxEvents")
  private Integer maxEvents = null;

  @SerializedName("returnImmediately")
  private Boolean returnImmediately = null;

  @SerializedName("ack")
  private List<String> ack = new ArrayList<String>();

  public PollEventsRequest maxEvents(Integer maxEvents) {
    this.maxEvents = maxEvents;
    return this;
  }

   /**
   * Get maxEvents
   * @return maxEvents
  **/
  @Schema(description = "")
  public Integer getMaxEvents() {
    return maxEvents;
  }

  public void setMaxEvents(Integer maxEvents) {
    this.maxEvents = maxEvents;
  }

  public PollEventsRequest returnImmediately(Boolean returnImmediately) {
    this.returnImmediately = returnImmediately;
    return this;
  }

   /**
   * Get returnImmediately
   * @return returnImmediately
  **/
  @Schema(description = "")
  public Boolean isReturnImmediately() {
    return returnImmediately;
  }

  public void setReturnImmediately(Boolean returnImmediately) {
    this.returnImmediately = returnImmediately;
  }

  public PollEventsRequest ack(List<String> ack) {
    this.ack = ack;
    return this;
  }

  public PollEventsRequest addAckItem(String ackItem) {
    this.ack.add(ackItem);
    return this;
  }

   /**
   * Get ack
   * @return ack
  **/
  @Schema(required = true, description = "")
  public List<String> getAck() {
    return ack;
  }

  public void setAck(List<String> ack) {
    this.ack = ack;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PollEventsRequest pollEventsRequest = (PollEventsRequest) o;
    return Objects.equals(this.maxEvents, pollEventsRequest.maxEvents) &&
        Objects.equals(this.returnImmediately, pollEventsRequest.returnImmediately) &&
        Objects.equals(this.ack, pollEventsRequest.ack);
  }

  @Override
  public int hashCode() {
    return Objects.hash(maxEvents, returnImmediately, ack);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PollEventsRequest {\n");
    
    sb.append("    maxEvents: ").append(toIndentedString(maxEvents)).append("\n");
    sb.append("    returnImmediately: ").append(toIndentedString(returnImmediately)).append("\n");
    sb.append("    ack: ").append(toIndentedString(ack)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
